### ISSUE TITLE
Vdebug don't start.No connection was made.

### ISSUE THREAD

**Issue by we138** [joonty/vdebug#235]
Hi, I try to start vdebug on local machine, but he can't run.I get this message "No connection was made".
My config:
Ubuntu 12.04/Apache/php5.4/Vim 7.3

_/etc/php5/conf.d/xdebug.ini_

``` zend_extension=/usr/lib/php5/20090626/xdebug.so
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
```

application working on 8080 port

**Comment by gl2748** [comment]
The best place to start with this issue is the troubleshooting help docs provided at `:h vdebug` within vim or here: `https://github.com/joonty/vdebug/blob/master/doc/Vdebug.txt#L1128`

For my part I ran the issue you describe and the solution was outside the immediate scope of the docs. That said I don't fully understand the solution and would appreciate any feedback on why it works.

Suffice it to say the issue was fixed in the following way:

### Background:

####  Install xdebug:
```
sudo apt-get install php5-cli, php5-xdebug
sudo php5enmod xdebug
```
so that `php -v` outputs:
```
PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethan
```
`/etc/php5/mods-available/xdebug.ini` looks like this:
```
zend_extension = xdebug.so
xdebug.remote_enable = on
```
Finally install vdebug as described in docs.

#### Testing the setup:

##### Create a basic script to exclude all possible errors. Something like: `~/tester.php`
```
<?php

print_r("hello" . "\r\n");
$var = 1;
xdebug_break();
$bromine = "Bratislava Cava";
xdebug_break();
```

1. Now press `f5` to initialize vdebug. You know it's working because it says it's listening for connections.  
2. Open a new terminal window and run the script `php tester.php`
3. Nothing :-1: 
4. Cancel the listening session with `ctrl+c`.
5. Start again with `f5`
6. Open a new terminal window and this time *Before* running the test script run: `export XDEBUG_CONFIG="remote_enable=1"` and now run the script `php tester.php`
7. :+1: 


Nothing.

Restart a listening session again with `f5`.

**Comment by cincodenada** [comment]
Indeed, go through what @gl2748 has said - but mainly, xdebug remote_enable requires something to trigger xdebug - either a cookie or GET parameter for web requests, or a environment variable for CLI, as detailed [over at the Xdebug docs](https://xdebug.org/docs/remote)

**Comment by l0rb** [comment]
This fixed my issue at the CLI but what if xdebug still does not connect to scripts that are run via opening them in a browser?
